### ISSUE TITLE
TypeError: optionDefinitions.flatMap is not a function

### ISSUE THREAD

**Issue by pietro-coretto** [FlamingTempura/bibtex-tidy#41]
I installed via `npm` and I get this

```sh
$ bibtex-tidy  myrefs.bib
/usr/local/lib/node_modules/bibtex-tidy/bin/bibtex-tidy:5342
var OPTIONS = new Set(optionDefinitions.flatMap((def) => Object.keys(def.cli)));
                                        ^
TypeError: optionDefinitions.flatMap is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/bibtex-tidy/bin/bibtex-tidy:5342:41)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

**Comment by FlamingTempura** [comment]
Could you check your node version?
```
node -v
```

Currently bibtex-tidy requires at least v11.15.

Could you also let me know your OS and how you installed node?

**Comment by pietro-coretto** [comment]
I am on  Linux Elementary OS 5.1 and it seems `apt` manager has node back to 8.x 
```sh
~$ node -v
v8.10.0
```

I tried to install it via snap but it didn't work. After some trial, I  completely removed node with 

```sh
apt-get purge node
```

and then I installed it from the official repo (instructions for debian/ubuntu distros) doing 

```sh
curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
apt-get install -y nodejs
```

The complete documentation is here

https://github.com/nodesource/distributions#debinstall
 
Therefore this solved the issue

Thanks
