### ISSUE TITLE
Running it locally fails

### ISSUE THREAD

**Issue by ianhellstrom** [FlamingTempura/bibtex-tidy#48]
I installed bibtex-tidy with npm as indicated on Ubuntu 2020.04 and when I run it I get the following error:

```
var OPTIONS = new Set(optionDefinitions.flatMap((def) => Object.keys(def.cli)));
                                        ^
TypeError: optionDefinitions.flatMap is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/bibtex-tidy/bin/bibtex-tidy:5342:41)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

The command I'm running it with is simply `bibtex-tidy refs.bib`. That file exists in the current directory.

**Comment by ianhellstrom** [comment]
It might be worth adding that NodeJs > v11 is required and perhaps v16 is recommended. That's not obvious to people who merely copy-paste the installation code.
